# Generated by Django 3.0.4 on 2020-03-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectLookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business object name', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fyle_org_id', models.CharField(help_text='Organisation id in Fyle', max_length=255)),
                ('fyle_refresh_token', models.CharField(help_text='Refresh Token', max_length=512)),
                ('current_state', models.CharField(help_text='Current state of backup', max_length=64)),
                ('name', models.CharField(help_text='Backup name', max_length=64)),
                ('task_id', models.CharField(help_text='Task reference for Fyle Jobs Infra', max_length=255, null=True)),
                ('filters', models.TextField(help_text='Request URL with filters and constraints')),
                ('data_format', models.CharField(help_text='Data format for backup', max_length=10)),
                ('error_message', models.CharField(help_text='Backup failure reason', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.ObjectLookup')),
            ],
        ),
    ]
